root = "scala_parser"

[scala_parser]
ParsedProject = "automatic_explorer"

[manual_explorer]
DesignPoint = "bash_generator"

[bash_generator]
DesignPoint = "verilog_parser"

[verilog_parser]
DesignPoint = "verilog_boxer"

[verilog_boxer]
DesignPoint = "vivado_builder"

[vivado_builder]
EvaluatedDesignPoint = "automatic_explorer"
EndExploration = "automatic_explorer"
