root = "verilog_parser"

[verilog_parser]
ParsedProject = "manual_explorer"

[manual_explorer]
DesignPoint = "verilog_boxer"

[verilog_boxer]
DesignPoint = "vivado_builder"

[vivado_builder]
EvaluatedDesignPoint = "manual_explorer"
EndExploration = "manual_explorer"
